<?php

namespace AppBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * MovieRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MovieRepository extends EntityRepository
{

    public function getAllMovies(){

        $qb = $this->createQueryBuilder('a');

        $query = $qb
            ->where("a.year > 2000")
            ->getQuery();

        return json_encode(array('movies' => $query->getResult()));

    }
}
